@rem Standard Gradle wrapper launcher (Windows).
@rem Requires gradle\wrapper\gradle-wrapper.jar, generated by Android Studio
@rem on first sync or by running `gradle wrapper` with a system Gradle.

@if "%DEBUG%"=="" @echo off
setlocal

set DIRNAME=%~dp0
set APP_HOME=%DIRNAME%
set CLASSPATH=%APP_HOME%gradle\wrapper\gradle-wrapper.jar

if not exist "%CLASSPATH%" (
  echo gradle-wrapper.jar is missing. Open this project in Android Studio once, 1>&2
  echo or run "gradle wrapper" with a system Gradle, to generate it. 1>&2
  exit /b 1
)

set JAVA_EXE=java.exe
if defined JAVA_HOME set JAVA_EXE=%JAVA_HOME%\bin\java.exe

"%JAVA_EXE%" -classpath "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %*
endlocal
