/**
 * The Gapture AI identity marker (DESIGN.md §24, §45). Every AI-generated
 * region carries this so it is never mistaken for the official regulatory
 * source (DESIGN.md §2.1).
 */
export function AILabel({ children = "Generated by Gapture AI" }: { children?: React.ReactNode }) {
  return (
    <span className="inline-flex items-center gap-1.5 rounded-full bg-ai/10 px-2 py-0.5 text-xs font-medium text-ai">
      <span aria-hidden>✦</span>
      {children}
    </span>
  );
}
